config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  # resources :users, only: [:show]
  resources :friendships, only: [:create, :destroy]

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'
  get 'home/index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stock#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  get 'users/:id', to: 'users#show', as: 'user'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  
end

app/models/stock.rb
class Stock < ApplicationRecord
 has_many :user_stocks
 has_many :users, through: :user_stocks

 validates :stock, :sector, presence: true

  def self.new_lookup(stock)
    client = IEX::Api::Client.new(publishable_token: ENV['publishable_api_key'],
                                  endpoint: 'https://cloud.iexapis.com/v1')
  
  begin

    
    bundle = client.get("tops?symbols=#{stock}", token: ENV['secret_api_key'])


    bundle = bundle[0]
  
    symbol = bundle["symbol"]

    sector = bundle["sector"]

    last_sale_price = bundle["lastSalePrice"]

    new(stock: symbol, sector: sector, last_price: last_sale_price)

    # return result = [symbol, sector, last_sale_price]
    
    rescue => exception 
      return false
    end
  end

  def self.check_db(stock)
    where(stock: stock).first
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(stock)
    stocks = current_user_stocks
    return false unless stocks
    stocks.where(stock: stock).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end 

  def can_track_stock?(stock)
    under_stock_limit? && !stock_already_tracked?(stock)
  end

  def current_user_stocks
    Stock.where(id: UserStock.where(user_id: id).pluck(:stock_id))
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name || first_name == nil || last_name == nil
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end


  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end

  def not_friends_with?(friend_id)
    !self.friends.where(id: friend_id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  respond_to :html, :json, :js  # not necessary? 

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def create
        friend = User.find params.require(:friend)
        current_user.friendships.build(friend_id: friend.id)
        if current_user.save
            flash[:notice] = "Following friend"
        else
            flash[:alert] = "There was something wrong with the tracking request"
        end
        redirect_to my_friends_path

    end

    def destroy
        friendship = Friendship.where(user_id: current_user.id, friend_id: params[:id]).first
        friendship.destroy
        flash[:notice] = "Stopped following"
        redirect_to my_friends_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/stock_controller.rb
class StockController < ApplicationController
    protect_from_forgery except: :search

    def search
        @user = current_user
        @tracked_stocks = current_user.stocks
        if params[:stock].present?
           @stock = Stock.new_lookup(params[:stock])
           if @stock 
            render 'users/my_portfolio'
           else
            flash[:alert] = "Please enter a valid symbol to search"
            redirect_to my_portfolio_path
           end
        else
           flash[:alert] = "Please enter a symbol to search" 
           redirect_to my_portfolio_path
        end
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:stock])
        if stock.blank?
            stock = Stock.new_lookup(params[:stock])
            stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock[0]} was successfully added to your portfolio"
        redirect_to my_portfolio_path
    end

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:notice] = "#{stock.stock} was successfully removed from your portfolio"
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @my_friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
    @my_friends = current_user.friends
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        render 'users/my_friends' 
      else
          flash[:alert] = "Couldn't find user"
          redirect_to my_friends_path
      end    
    else
        flash[:alert] = "Please enter a friend name or email to search"
        redirect_to my_friends_path 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-bordered table-dark table-hover">
          <thead>
            <tr>
              <th scope="col">Email</th>
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @my_friends.each do |friend| %>
             <tr>
               <th scope="row"><%= friend.email %></th>
               <td><%= friend.first_name %></td>
               <td><%= friend.last_name %></td>
               <td>
                    <%= link_to 'View Profile', user_path(friend),
                                          class: 'btn btn-sm btn-success' %>
                    <%= button_to 'Stop Following', friendship_path(friend), data: {confirm: 'Are you sure?'},
                       class: 'btn btn-sm btn-warning', :method => :delete %></td>
             </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

app/views/home/index.html.erb
<h1>Welcome to the Finance Tracker app!</h1>
<p>Log in or create and account</p>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
   <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
   <% if current_user %>

       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>

       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
           <li class="nav-item <%= 'active' if request.path == my_portfolio_path%>">
             <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link'%>
           </li>
           <li class="nav-item">
             <%= link_to 'My Friends', my_friends_path, class: 'nav-link'%>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Profile
             </a>  
             <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
               <%= fa_icon 'edit' %> Edit Profile 
               <% end %>
                <div class="dropdown-divider"></div>
               <a class="dropdown-item" href="#">Another action</a>
               <div class="dropdown-divider"></div>
               <a class="dropdown-item" href="#">Something else here</a>
             </div>
           </li>
        </ul>
        <ul class='navbar-nav ml-auto'>
          <li class='nav-item user-name'>
            <%= fa_icon 'user' %> <%= current_user.full_name %>
          </li>
          <li class='nav-item'>
            <%= link_to("Logout", destroy_user_session_path,
                class: "btn btn-xs btn-danger logout-button", method: :delete)%>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
         </form>
       </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/stocks/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-bordered table-dark table-hover">
          <thead>
            <tr>
              <th scope="col">Stock</th>
              <th scope="col">Sector</th>
              <th scope="col">Price</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @tracked_stocks.each do |stock| %>
             <tr>
               <th scope="row"><%= stock.stock %></th>
               <td><%= stock.sector %></td>
               <td><%= stock.last_price %></td>
               <td><% if current_user.can_track_stock?(stock.stock) %>
                    <%= button_to 'Add to portfolio', user_stocks_path(user: :current_user, stock: stock[:stock]),
                                                    class: "btn btn-xs btn-success", :method => :post %>

                    <% elsif current_user.id != @user.id %>

                        <span class="badge badge-secondary">
                            You are already tracking
                            <% if !current_user.under_stock_limit? %>
                                10 stocks
                            <% end %>
                            <% if current_user.stock_already_tracked?(stock.stock) %>
                                this stock
                            <% end %>
                        </span>
                    <% end %>
                <% if current_user.id == @user.id %>
               <%= button_to 'Remove', user_stock_path(stock), data: {confirm: 'Are you sure?'},
                       class: 'btn btn-sm btn-warning', :method => :delete %>
                <% end %>  
                </td>
             </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
  <div class="card card-header results-block">
    <% @friends.each do |friend| %>
      <strong>Name: </strong> <%= friend.full_name %>
      <strong>Email: </strong> <%= friend.email %>
      <strong>Profile: </strong> <%= link_to "View Profile", user_path(friend),
                              class: "btn btn-sm btn-success" %>
    <% if current_user.not_friends_with?(friend.id) %>
      <%= button_to 'Follow friend?', friendships_path(friend: friend),
                              class: "btn btn-sm btn-success", :method => :post %>
    <% else %>
      <span class="badge badge-secondary">
      You are already friends
      </span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_result.html.erb
<!-- I dont think I need this but it's here anyways for the moment -->
<div class="results-block ">
    <%= render 'layouts/messages' %>
</div>

<% if @stock %>
<div class="card card-header">
    <strong> Symbol: </strong> <%= @stock[:stock] %>
    <strong> Sector: </strong> <%= @stock[:sector] %>
    <strong> Price: </strong> <%= @stock[:last_price] %>
    <% if current_user.can_track_stock?(@stock.stock) %>
    <%= button_to 'Add to portfolio', user_stocks_path(user: :current_user, stock: @stock[:stock]),
                                    class: "btn btn-xs btn-success", :method => :post %>

    <% else %>

        <span class="badge badge-secondary">
            You are already tracking
            <% if !current_user.under_stock_limit? %>
                10 stocks
            <% end %>
            <% if current_user.stock_already_tracked?(@stock.stock) %>
                this stock
            <% end %>
        </span>
    <% end %>
  </div>
<% end %>

app/views/users/my_friends.html.erb
<h1>Friends</h1>

<div class='search-area'>
    <h3>Search Friends</h3>
    <%= form_tag search_friend_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :friend, params[:friend], placeholder: "Enter friend name or email", autofocus: true, class: "form-control form-control-lg" %>
                
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<%= render 'users/friend_result' %>


<% if !@my_friends.empty? %>
    <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class='search-area'>
    <h3>Search Stocks</h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock Ticker Symbol", autofocus: true, class: "form-control form-control-lg" %>
                
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<%= render 'users/result' %>

<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>


<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td>
          <% if current_user.not_friends_with?(@user.id) %>
            <%= link_to 'Follow friend?', friendships_path(friend: @user),
                          class: "btn btn-sm btn-success", method: :post %>
          <% else %>
            <span class="badge badge-secondary">
              You are friends
            </span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% else %>
  <p class='lead'>This user is not tracking any stocks</p>
<% end %>
<%= link_to 'Back', my_friends_path, class: "btn btn-primary" %>